### ISSUE TITLE
Maven wrapper batch file for windows does not work

### ISSUE THREAD

**Issue by smm13344331** [UniconLabs/simple-cas4-overlay-template#18]
In mvnw.bat line 100:
if exist "%M2_HOME%\bin\mvn.cmd" goto init
should be:
if exist "%M2_HOME%\bin\mvn.bat" goto init
to make it work.

System Environment:
Windows 10
apache-maven-3.2.5

**Comment by scalding** [comment]
Note that newer versions of maven use `mvn.cmd` rthar than `mvn.bat`. You're likely going to want to update.

Beyond that, there seems to be a deficiency since the wrapper should not require an installation of maven. That is, you should run the wrapper and the wrapper should download an appropriate version of Maven for use.

**Comment by smm13344331** [comment]
You are correct, I have updated my maven and the problem resolved but for some reason it failed with another error:
-Dmaven.multiModuleProjectDirectory system properly is not set. Check $M2_HOME environment variable and mvn script match.

which I have managed to solve it by adding:
-Dmaven.multiModuleProjectDirectory=%$M2_HOME%
to mvn.bat line 152:
%MAVEN_JAVA_EXE% %JVM_CONFIG_MAVEN_PROPS% %MAVEN_OPTS% %MAVEN_DEBUG_OPTS% -classpath %WRAPPER_JAR% %WRAPPER_LAUNCHER% %MAVEN_CMD_LINE_ARGS%

Thank you @scalding for your fast response.
